version: '3'

services:
  db:
    container_name: postgres
    restart: always
    build:
      context: ./db/
      dockerfile: Dockerfile
    env_file:
     - ./db.env
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./db/dump.sql:/data/dump.sql
